names = ('Monica', 'Tom', 'John', 'Michael')
sorted_names = tuple(sorted(names))
names_arr = list(names)
#print(names_arr[0], names_arr[1], names_arr[2], names_arr[3])
#print(names_arr)
#names_arr.sort()
#print(names_arr)
#names_t = tuple(names_arr)
print(sorted_names)
